/**
 * GENERATED FILE - do not edit by hand.
 * Regenerate with: npm run update:crawlers
 *
 * Source: ai.robots.txt community dataset (https://raw.githubusercontent.com/ai-robots-txt/ai.robots.txt/main/robots.json),
 * fetched 2026-09-09.
 * 174 crawlers total: 19 curated + 155 community;
 * 82 flagged dualUse (also power search/retrieval or
 * user-initiated fetching a site may want to keep).
 */

export type AICrawler = {
  userAgent: string;
  operator: string;
  purpose: string;
  /** true if this crawler also powers a search/discovery product users may want to keep */
  dualUse?: boolean;
};

export const AI_CRAWLERS: AICrawler[] = [
  { userAgent: "GPTBot", operator: "OpenAI", purpose: "LLM training data collection" },
  { userAgent: "OAI-SearchBot", operator: "OpenAI", purpose: "ChatGPT Search index", dualUse: true },
  { userAgent: "ChatGPT-User", operator: "OpenAI", purpose: "Real-time user-initiated fetching", dualUse: true },
  { userAgent: "Google-Extended", operator: "Google", purpose: "Gemini / Vertex AI training", dualUse: true },
  { userAgent: "ClaudeBot", operator: "Anthropic", purpose: "LLM training data collection" },
  { userAgent: "Claude-Web", operator: "Anthropic", purpose: "Legacy web fetch" },
  { userAgent: "anthropic-ai", operator: "Anthropic", purpose: "AI assistant fetching" },
  { userAgent: "CCBot", operator: "Common Crawl", purpose: "Open dataset used by many model trainers" },
  { userAgent: "Bytespider", operator: "ByteDance", purpose: "TikTok / Doubao LLM training" },
  { userAgent: "PerplexityBot", operator: "Perplexity", purpose: "Answer engine index + training", dualUse: true },
  { userAgent: "Amazonbot", operator: "Amazon", purpose: "Alexa / Nova training", dualUse: true },
  { userAgent: "Applebot-Extended", operator: "Apple", purpose: "Apple Intelligence training (opt-in for Siri search kept via Applebot)", dualUse: true },
  { userAgent: "Meta-ExternalAgent", operator: "Meta", purpose: "LLaMA training data collection" },
  { userAgent: "YouBot", operator: "You.com", purpose: "Answer engine index + training", dualUse: true },
  { userAgent: "Diffbot", operator: "Diffbot", purpose: "Knowledge-graph / dataset extraction" },
  { userAgent: "Cotoyogi", operator: "NII (Japan)", purpose: "Research LLM corpus" },
  { userAgent: "Timpibot", operator: "Timpi", purpose: "Web-scale dataset" },
  { userAgent: "iaskspider", operator: "iAsk.AI", purpose: "LLM training data collection" },
  { userAgent: "ImagesiftBot", operator: "Hive", purpose: "Image dataset collection" },
  { userAgent: "AddSearchBot", operator: "Unclear at this time.", purpose: "AI Search Crawlers", dualUse: true },
  { userAgent: "AgentTimes", operator: "The Agent Times", purpose: "Data Scraper from RSS Feeds." },
  { userAgent: "AI2Bot", operator: "Ai2", purpose: "Content is used to train open language models." },
  { userAgent: "AI2Bot-DeepResearchEval", operator: "Ai2, a non-profit AI research institute", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Ai2Bot-Dolma", operator: "Ai2", purpose: "Content is used to train open language models." },
  { userAgent: "aiHitBot", operator: "aiHit", purpose: "A massive, artificial intelligence/machine learning, automated system." },
  { userAgent: "AIWebIndex", operator: "Lyrenth", purpose: "AI Search Crawlers", dualUse: true },
  { userAgent: "amazon-kendra", operator: "Amazon", purpose: "Collects data for AI natural language search", dualUse: true },
  { userAgent: "amazon-QBusiness", operator: "Unclear at this time.", purpose: "AI Assistants", dualUse: true },
  { userAgent: "AmazonBuyForMe", operator: "Amazon", purpose: "AI Agents" },
  { userAgent: "Amzn-SearchBot", operator: "Unclear at this time.", purpose: "AI Search Crawlers", dualUse: true },
  { userAgent: "Amzn-User", operator: "Amazon, used for fetching web content to answer user queries through Alexa and other Amazon AI services", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Andibot", operator: "Andi", purpose: "Search engine using generative AI, AI Search Assistant", dualUse: true },
  { userAgent: "Anomura", operator: "Direqt", purpose: "Collects data for AI search", dualUse: true },
  { userAgent: "ApifyBot", operator: "Unclear at this time.", purpose: "AI Data Providers" },
  { userAgent: "ApifyWebsiteContentCrawler", operator: "Unclear at this time.", purpose: "AI Data Providers" },
  { userAgent: "Applebot", operator: "Unclear at this time.", purpose: "AI Search Crawlers", dualUse: true },
  { userAgent: "Aranet-SearchBot", operator: "Unclear at this time.", purpose: "Undocumented AI Agents" },
  { userAgent: "atlassian-bot", operator: "Atlassian", purpose: "AI search, assistants and agents", dualUse: true },
  { userAgent: "Awario", operator: "Awario", purpose: "AI Data Scrapers" },
  { userAgent: "AzureAI-SearchBot", operator: "Unclear at this time.", purpose: "AI Search Crawlers", dualUse: true },
  { userAgent: "bedrockbot", operator: "Amazon", purpose: "Data scraping for custom AI applications." },
  { userAgent: "bigsur.ai", operator: "Big Sur AI that fetches website content to enable AI-powered web agents, sales assistants, and content marketing solutions for busi…", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Bravebot", operator: "Unknown", purpose: "AI Data Providers" },
  { userAgent: "Brightbot", operator: "Unclear at this time.", purpose: "AI Data Providers" },
  { userAgent: "Brightbot 1.0", operator: "Unknown", purpose: "LLM/AI training." },
  { userAgent: "BuddyBot", operator: "BuddyBotLearning", purpose: "AI Learning Companion" },
  { userAgent: "Channel3Bot", operator: "Unclear at this time.", purpose: "AI Search Crawlers", dualUse: true },
  { userAgent: "ChatGLM-Spider", operator: "Unclear at this time.", purpose: "AI Data Scrapers" },
  { userAgent: "ChatGPT Agent", operator: "OpenAI", purpose: "AI Agents", dualUse: true },
  { userAgent: "Claude-Code", operator: "Unclear at this time.", purpose: "AI Coding Agents", dualUse: true },
  { userAgent: "Claude-SearchBot", operator: "Anthropic", purpose: "Claude-SearchBot navigates the web to improve search result quality for users. It analyzes online content specifically to enhance the relevance and accuracy of search responses.", dualUse: true },
  { userAgent: "Claude-User", operator: "Anthropic", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Cloudflare-AutoRAG", operator: "Cloudflare", purpose: "Collects data for AI search", dualUse: true },
  { userAgent: "CloudVertexBot", operator: "Unclear at this time.", purpose: "AI Data Scrapers" },
  { userAgent: "Code", operator: "Unclear at this time.", purpose: "AI Coding Agents", dualUse: true },
  { userAgent: "cohere-ai", operator: "Cohere", purpose: "Retrieves data to provide responses to user-initiated prompts.", dualUse: true },
  { userAgent: "cohere-training-data-crawler", operator: "Cohere to download training data for its LLMs (Large Language Models) that power its enterprise AI products", purpose: "AI Data Scrapers" },
  { userAgent: "CragCrawler", operator: "CragSoftware, a Brazil-based software company specializing in data engineering and AI web scraping services", purpose: "AI Data Providers" },
  { userAgent: "Crawl4AI", operator: "Unclear at this time.", purpose: "Undocumented AI Agents" },
  { userAgent: "Crawlspace", operator: "Crawlspace", purpose: "AI Data Providers" },
  { userAgent: "Cursor", operator: "Unclear at this time.", purpose: "AI Coding Agents", dualUse: true },
  { userAgent: "Datenbank Crawler", operator: "Datenbank", purpose: "AI Data Scrapers" },
  { userAgent: "DeepSeekBot", operator: "DeepSeek", purpose: "Training language models and improving AI products" },
  { userAgent: "Devin", operator: "Devin AI", purpose: "AI Coding Agents", dualUse: true },
  { userAgent: "Diffbot-User", operator: "Diffbot", purpose: "AI Assistants", dualUse: true },
  { userAgent: "DoubaoBot", operator: "ByteDance", purpose: "AI crawler for ByteDance's Doubao AI assistant.", dualUse: true },
  { userAgent: "DuckAssistBot", operator: "Unclear at this time.", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Echobot Bot", operator: "Echobox", purpose: "AI Data Scrapers" },
  { userAgent: "EchoboxBot", operator: "Echobox", purpose: "Data collection to support AI-powered products." },
  { userAgent: "ERNIEBot", operator: "Baidu", purpose: "Collects public web content for Baidu's ERNIE large language models." },
  { userAgent: "ExaBot", operator: "Unclear at this time.", purpose: "AI Data Providers" },
  { userAgent: "ExaSearchBot", operator: "Exa", purpose: "AI Search Crawlers", dualUse: true },
  { userAgent: "FacebookBot", operator: "Meta/Facebook", purpose: "Training language models" },
  { userAgent: "facebookexternalhit", operator: "Meta/Facebook", purpose: "Ostensibly only for sharing, but likely used as an AI crawler as well" },
  { userAgent: "Factset_spyderbot", operator: "Factset", purpose: "AI model training." },
  { userAgent: "FirecrawlAgent", operator: "Firecrawl that extracts web content and converts it into structured data for use in LLM and AI applications", purpose: "AI Data Providers" },
  { userAgent: "FriendlyCrawler", operator: "Unknown", purpose: "We are using the data from the crawler to build datasets for machine learning experiments." },
  { userAgent: "GeistHaus-PageFetcher", operator: "GeistHaus, a company developing AI systems for therapy and psychological assessment", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Gemini-Deep-Research", operator: "Unclear at this time.", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Google-Agent", operator: "Unclear at this time.", purpose: "AI Agents", dualUse: true },
  { userAgent: "Google-CloudVertexBot", operator: "Google", purpose: "Build and manage AI models for businesses employing Vertex AI" },
  { userAgent: "Google-Firebase", operator: "Google", purpose: "Used as part of AI apps developed by users of Google's Firebase AI products." },
  { userAgent: "Google-Gemini-CLI", operator: "Unclear at this time.", purpose: "AI Coding Agents", dualUse: true },
  { userAgent: "Google-NotebookLM", operator: "Unclear at this time.", purpose: "AI Assistants", dualUse: true },
  { userAgent: "GoogleAgent-Mariner", operator: "Google", purpose: "AI Agents", dualUse: true },
  { userAgent: "GoogleAgent-URLContext", operator: "Google that retrieves web content on behalf of Gemini API users", purpose: "AI Assistants", dualUse: true },
  { userAgent: "GoogleOther", operator: "Google", purpose: "Scrapes data.", dualUse: true },
  { userAgent: "GoogleOther-Image", operator: "Google", purpose: "Scrapes data.", dualUse: true },
  { userAgent: "GoogleOther-Video", operator: "Google", purpose: "Scrapes data.", dualUse: true },
  { userAgent: "HenkBot", operator: "Unclear at this time.", purpose: "AI Data Providers" },
  { userAgent: "iAskBot", operator: "Unclear at this time.", purpose: "Undocumented AI Agents" },
  { userAgent: "iaskspider/2.0", operator: "iAsk", purpose: "Crawls sites to provide answers to user queries." },
  { userAgent: "ICC-Crawler", operator: "NICT", purpose: "Scrapes data to train and support AI technologies." },
  { userAgent: "imageSpider", operator: "Unclear at this time.", purpose: "AI Data Scrapers" },
  { userAgent: "img2dataset", operator: "img2dataset", purpose: "Scrapes images for use in LLMs." },
  { userAgent: "ISSCyberRiskCrawler", operator: "ISS-Corporate", purpose: "Scrapes data to train machine learning models." },
  { userAgent: "kagi-fetcher", operator: "Kagi that fetches web content to answer user queries through Kagi AI, their suite of AI-powered tools including Assistant, Res…", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Kangaroo Bot", operator: "Unclear at this time.", purpose: "AI Data Scrapers" },
  { userAgent: "Kimi-SearchBot", operator: "Moonshot AI", purpose: "AI Search Crawlers", dualUse: true },
  { userAgent: "Kimi-User", operator: "Moonshot AI that fetches web content on behalf of users interacting with Kimi", purpose: "AI Assistants", dualUse: true },
  { userAgent: "KimiBot", operator: "Moonshot AI", purpose: "AI Data Scrapers" },
  { userAgent: "KlaviyoAIBot", operator: "Klaviyo", purpose: "AI Assistants", dualUse: true },
  { userAgent: "KunatoCrawler", operator: "Unclear at this time.", purpose: "Undocumented AI Agents" },
  { userAgent: "laion-huggingface-processor", operator: "Unclear at this time.", purpose: "AI Data Scrapers" },
  { userAgent: "LAIONDownloader", operator: "Large-scale Artificial Intelligence Open Network", purpose: "AI tools and models for machine learning research.", dualUse: true },
  { userAgent: "LCC", operator: "Unclear at this time.", purpose: "AI Data Scrapers" },
  { userAgent: "Lightpanda", operator: "Anyone who downloads the Lightpanda client. Possibly being used by a Grok-adjacent organization's botnet.", purpose: "AI Data Scrapers" },
  { userAgent: "LinerBot", operator: "Unclear at this time.", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Linguee Bot", operator: "Linguee", purpose: "AI powered translation service" },
  { userAgent: "LinkupBot", operator: "Unclear at this time.", purpose: "AI Search Crawlers", dualUse: true },
  { userAgent: "Manus-User", operator: "Butterfly Effect, a company based in China", purpose: "AI Agents", dualUse: true },
  { userAgent: "meta-externalfetcher", operator: "Unclear at this time.", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Meta-ExternalFetcher", operator: "Unclear at this time.", purpose: "AI Assistants", dualUse: true },
  { userAgent: "meta-webindexer", operator: "Meta", purpose: "AI Assistants", dualUse: true },
  { userAgent: "MistralAI-Index", operator: "Mistral AI", purpose: "Indexes web content for Mistral AI's search, used to answer questions in Le Chat. Per Mistral, not used for model training.", dualUse: true },
  { userAgent: "MistralAI-Training", operator: "Mistral AI", purpose: "AI Data Scrapers" },
  { userAgent: "MistralAI-User", operator: "Mistral", purpose: "AI Assistants", dualUse: true },
  { userAgent: "MistralAI-User/1.0", operator: "Mistral AI", purpose: "Takes action based on user prompts." },
  { userAgent: "Mozilla-Tabstack", operator: "Mozilla that performs programmatic, AI-driven interactions with web content through Tabstack", purpose: "AI Data Providers" },
  { userAgent: "MyCentralAIScraperBot", operator: "Unclear at this time.", purpose: "AI data scraper" },
  { userAgent: "NagetBot", operator: "Naget Inc (founded by Chris Samarinas, headquarter in Amherst, Massachusetts)", purpose: "AI data scraper", dualUse: true },
  { userAgent: "netEstate Imprint Crawler", operator: "netEstate", purpose: "AI Data Scrapers" },
  { userAgent: "newsai", operator: "Unclear at this time.", purpose: "AI data scraper", dualUse: true },
  { userAgent: "NotebookLM", operator: "Unclear at this time.", purpose: "AI Assistants", dualUse: true },
  { userAgent: "NovaAct", operator: "Unclear at this time.", purpose: "AI Agents", dualUse: true },
  { userAgent: "OAI-AdsBot", operator: "OpenAI", purpose: "Validates and targets ads on ChatGPT." },
  { userAgent: "omgili", operator: "Webz.io", purpose: "Data is sold.", dualUse: true },
  { userAgent: "omgilibot", operator: "Webz.io", purpose: "Data is sold.", dualUse: true },
  { userAgent: "OpenAI", operator: "OpenAI", purpose: "The purpose of this bot is unclear at this time but it is a member of OpenAI's suite of crawlers." },
  { userAgent: "opencode", operator: "Unclear at this time.", purpose: "AI Coding Agents", dualUse: true },
  { userAgent: "Operator", operator: "Unclear at this time.", purpose: "AI Agents", dualUse: true },
  { userAgent: "PanguBot", operator: "the Chinese company Huawei", purpose: "AI Data Scrapers" },
  { userAgent: "Panscient", operator: "Panscient", purpose: "Data collection and analysis using machine learning and AI." },
  { userAgent: "panscient.com", operator: "Panscient", purpose: "Data collection and analysis using machine learning and AI." },
  { userAgent: "Perplexity-User", operator: "Perplexity", purpose: "AI Assistants", dualUse: true },
  { userAgent: "PetalBot", operator: "Huawei", purpose: "Used to provide recommendations in Hauwei assistant and AI search services.", dualUse: true },
  { userAgent: "PhindBot", operator: "phind", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Poggio-Citations", operator: "Poggio, a company that provides AI sales enablement tools for creating tailored narratives, business cases, and account plan…", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Poseidon Research Crawler", operator: "Poseidon Research", purpose: "AI research crawler", dualUse: true },
  { userAgent: "QualifiedBot", operator: "Qualified", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Querit-SearchBot", operator: "Querit that indexes web content for their search API service, which is designed to provide real-time search results for larg…", purpose: "AI Data Providers" },
  { userAgent: "QueritBot", operator: "Querit, a company providing a search API for large language model integration", purpose: "AI Data Providers" },
  { userAgent: "QuillBot", operator: "Quillbot", purpose: "Company offers AI detection, writing tools and other services." },
  { userAgent: "quillbot.com", operator: "Quillbot", purpose: "Company offers AI detection, writing tools and other services." },
  { userAgent: "QwenBot", operator: "Alibaba", purpose: "Collects public web content for Alibaba's Qwen (Tongyi Qianwen) large language models." },
  { userAgent: "Reflectionbot", operator: "Reflection", purpose: "Undocumented AI Agents" },
  { userAgent: "SBIntuitionsBot", operator: "SB Intuitions", purpose: "Uses data gathered in AI development and information analysis." },
  { userAgent: "Scrapy", operator: "Zyte", purpose: "Scrapes data for a variety of uses including training AI." },
  { userAgent: "SemrushBot-OCOB", operator: "Semrush", purpose: "Crawls your site for ContentShake AI tool." },
  { userAgent: "SemrushBot-SWA", operator: "Semrush", purpose: "Checks URLs on your site for SEO Writing Assistant.", dualUse: true },
  { userAgent: "Shap-User", operator: "Unclear at this time.", purpose: "AI Assistants", dualUse: true },
  { userAgent: "ShapBot", operator: "Parallel", purpose: "AI Data Providers" },
  { userAgent: "Sidetrade indexer bot", operator: "Sidetrade", purpose: "Extracts data for a variety of uses including training AI." },
  { userAgent: "Spider", operator: "Unclear at this time.", purpose: "AI Data Scrapers" },
  { userAgent: "TavilyBot", operator: "Unclear at this time.", purpose: "AI Data Providers" },
  { userAgent: "Terra Cotta", operator: "Unclear at this time.", purpose: "AI Data Providers" },
  { userAgent: "TerraCotta", operator: "Ceramic AI", purpose: "AI Data Providers" },
  { userAgent: "Thinkbot", operator: "Thinkbot", purpose: "Insights on AI integration and automation." },
  { userAgent: "TikTokSpider", operator: "ByteDance", purpose: "LLM training." },
  { userAgent: "TongyiBot", operator: "Alibaba that fetches web content for the Tongyi Qianwen assistant and related Qwen-generated answers", purpose: "AI Assistants", dualUse: true },
  { userAgent: "Trae", operator: "Unclear at this time.", purpose: "AI Coding Agents", dualUse: true },
  { userAgent: "TwinAgent", operator: "Twin, a platform that creates automated workers to perform tasks by integrating with APIs and controlling web applications through browser automa…", purpose: "AI Agents" },
  { userAgent: "UseAI", operator: "Unclear at this time.", purpose: "AI Assistants", dualUse: true },
  { userAgent: "VelenPublicWebCrawler", operator: "Velen Crawler", purpose: "Scrapes data for business data sets and machine learning models." },
  { userAgent: "WARDBot", operator: "WEBSPARK", purpose: "AI Data Scrapers" },
  { userAgent: "webzio-extended", operator: "Unclear at this time.", purpose: "AI Data Scrapers" },
  { userAgent: "Webzio-Extended", operator: "Unclear at this time.", purpose: "AI Data Scrapers" },
  { userAgent: "wpbot", operator: "QuantumCloud", purpose: "Live chat support and lead generation.", dualUse: true },
  { userAgent: "WRTNBot", operator: "Unclear at this time.", purpose: "Undocumented AI Agents" },
  { userAgent: "YaK", operator: "Meltwater", purpose: "According to the [Meltwater Consumer Intelligence page](https://www.meltwater.com/en/suite/consumer-intelligence) 'By applying AI, data science, and market research expertise to a live feed of global data sources, we transform unstructured data into actionable insights allowing better decision-making'.", dualUse: true },
  { userAgent: "YandexAdditional", operator: "Yandex", purpose: "Scrapes/analyzes data for the YandexGPT LLM.", dualUse: true },
  { userAgent: "YandexAdditionalBot", operator: "Yandex", purpose: "Scrapes/analyzes data for the YandexGPT LLM.", dualUse: true },
  { userAgent: "YiyanBot", operator: "Baidu that fetches web content for the yiyan", purpose: "AI Assistants", dualUse: true },
  { userAgent: "ZanistaBot", operator: "Unclear at this time.", purpose: "AI Search Crawlers", dualUse: true },
];
