/**
 * Generator: produces all deployable opt-out artifacts from a scan result.
 * 1. robots.txt block snippet for known AI crawlers
 * 2. ai.txt (Spawning-style machine-readable permissions file)
 * 3. HTML <meta> tags
 * 4. EU DSM Art. 4(3) reservation statement (legal notice)
 */
import { AI_CRAWLERS, LEGAL } from "./crawlers";
import type { ScanResult } from "./scanner";

export type GeneratedArtifacts = {
  robotsSnippet: string;
  fullRobotsTxt: string;
  aiTxt: string;
  metaTags: string;
  legalNotice: string;
  rslXml: string;
};

export function generateRobotsSnippet(blocked: string[]): string {
  if (!blocked.length) return "";
  const lines = [
    "# ==== AI training crawler opt-out (generated by Don't Train On Me) ====",
    "# Machine-readable rights reservation per EU DSM Directive (EU) 2019/790 Art. 4(3)",
    "",
  ];
  // Group all AI UAs into one group with a blanket disallow — valid per RFC 9309.
  for (const ua of blocked) lines.push(`User-agent: ${ua}`);
  lines.push("Disallow: /");
  return lines.join("\n");
}

export function generateAiTxt(domain: string): string {
  return [
    "# ai.txt — machine-readable AI access policy",
    "# Spec: Spawning AI ai.txt proposal (https://spawning.ai/documents/ai.txt)",
    `# Domain: ${domain}`,
    `# Generated: ${new Date().toISOString()}`,
    "",
    "User-Agent: *",
    "Permission: deny-training",
    "Permission: deny-dataset",
    "Permission: deny-inference-prompting",
    "",
    LEGAL.euReservation,
  ].join("\n");
}

export function generateMetaTags(): string {
  return `<meta name="robots" content="noai, noimageai">`;
}

export function generateLegalNotice(domain: string): string {
  return [
    `# Notice of Reserved Rights — ${domain}`,
    "",
    LEGAL.notice,
    "",
    LEGAL.euReservation.replace(/^# /gm, ""),
  ].join("\n");
}

/**
 * RSL 1.0 license document (rslstandard.org schema, verified against the
 * official Getting Started guide). Default posture: prohibit AI training/input,
 * matching our opt-out stance. Creators can swap in a payment/custom template.
 */
export function generateRsl(): string {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rsl xmlns="https://rslstandard.org/rsl">',
    '  <content url="/">',
    '    <!-- AI training and AI-input prohibited; web search and human use permitted -->',
    '    <license>',
    '      <prohibits type="usage">ai-train ai-input</prohibits>',
    '    </license>',
    '  </content>',
    '</rsl>',
  ].join("\n");
}

export function generateAllArtifacts(scan: ScanResult): GeneratedArtifacts {
  // Block everything still open; keep already-blocked ones too so the
  // snippet is a complete drop-in replacement.
  const toBlock = scan.openCrawlers.length ? scan.openCrawlers : AI_CRAWLERS.map((c) => c.userAgent);
  const robots = generateRobotsSnippet(toBlock);
  return {
    robotsSnippet: robots,
    fullRobotsTxt:
      (scan.robotsFound ? "# Append the section below to your existing robots.txt\n\n" : "") +
      robots +
      `\n# RSL 1.0 machine-readable license (Really Simple Licensing)\nLicense: ${scan.url}/license.xml`,
    aiTxt: generateAiTxt(scan.url),
    metaTags: generateMetaTags(),
    legalNotice: generateLegalNotice(scan.url),
    rslXml: generateRsl(),
  };
}

/**
 * Protection score inputs — decoupled from ScanResult so /api/verify
 * can score user-pasted robots.txt content identically.
 */
export type ScoreInput = {
  blockedCount: number;
  totalCrawlers: number;
  hasNoaiMeta: boolean;
  aiTxtFound: boolean;
  reachable: boolean;
};

export function computeScore(input: ScoreInput): {
  score: number;
  breakdown: { label: string; got: number; max: number }[];
} {
  const crawlerCoverage = input.totalCrawlers > 0 ? input.blockedCount / input.totalCrawlers : 0;
  const breakdown = [
    { label: "AI crawlers blocked in robots.txt", got: Math.round(crawlerCoverage * 50), max: 50 },
    { label: "noai/noimageai meta tags", got: input.hasNoaiMeta ? 20 : 0, max: 20 },
    { label: "ai.txt published", got: input.aiTxtFound ? 15 : 0, max: 15 },
    { label: "Site reachable for verification", got: input.reachable ? 15 : 0, max: 15 },
  ];
  return {
    score: breakdown.reduce((s, b) => s + b.got, 0),
    breakdown,
  };
}

export function scoreFromScan(scan: ScanResult, totalCrawlers: number) {
  return computeScore({
    blockedCount: scan.blockedCrawlers.length,
    totalCrawlers,
    hasNoaiMeta:
      scan.metaTagsFound.includes("noai") || scan.metaTagsFound.includes("noimageai"),
    aiTxtFound: scan.aiTxtFound,
    reachable: scan.reachable,
  });
}
