/**
 * Generator: produces all deployable opt-out artifacts from a scan result.
 * 1. robots.txt block snippet for known AI crawlers
 * 2. ai.txt (Spawning-style machine-readable permissions file)
 * 3. HTML <meta> tags (noai/noimageai + W3C TDMRep reservation)
 * 4. EU DSM Art. 4(3) reservation statement (legal notice)
 */
import { AI_CRAWLERS, LEGAL } from "./crawlers.ts";
import type { ScanResult } from "./scanner.ts";
import { scoreFromLayers } from "./layers.ts";

export type GeneratedArtifacts = {
  robotsSnippet: string;
  fullRobotsTxt: string;
  aiTxt: string;
  metaTags: string;
  legalNotice: string;
  rslXml: string;
};

export function generateRobotsSnippet(blocked: string[]): string {
  if (!blocked.length) return "";
  const lines = [
    "# ==== AI training crawler opt-out (generated by Don't Train On Me) ====",
    "# Machine-readable rights reservation per EU DSM Directive (EU) 2019/790 Art. 4(3)",
    "",
  ];
  // Group all AI UAs into one group with a blanket disallow — valid per RFC 9309.
  for (const ua of blocked) lines.push(`User-agent: ${ua}`);
  lines.push("Disallow: /");
  return lines.join("\n");
}

export function generateAiTxt(domain: string): string {
  return [
    "# ai.txt — machine-readable AI access policy",
    "# Spec: Spawning AI ai.txt proposal (https://spawning.ai/documents/ai.txt)",
    `# Domain: ${domain}`,
    `# Generated: ${new Date().toISOString()}`,
    "",
    "User-Agent: *",
    "Permission: deny-training",
    "Permission: deny-dataset",
    "Permission: deny-inference-prompting",
    "",
    LEGAL.euReservation,
  ].join("\n");
}

export function generateMetaTags(): string {
  // noai/noimageai = page-level AI opt-out; tdm-reservation = W3C TDMRep,
  // the machine-readable EU DSM Art. 4(3) rights reservation.
  return [
    `<meta name="robots" content="noai, noimageai">`,
    `<meta name="tdm-reservation" content="1">`,
  ].join("\n");
}

export function generateLegalNotice(domain: string): string {
  return [
    `# Notice of Reserved Rights — ${domain}`,
    "",
    LEGAL.notice,
    "",
    LEGAL.euReservation.replace(/^# /gm, ""),
  ].join("\n");
}

/**
 * RSL 1.0 license document (rslstandard.org schema, verified against the
 * official Getting Started guide). Default posture: prohibit AI training/input,
 * matching our opt-out stance. Creators can swap in a payment/custom template.
 */
export function generateRsl(): string {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rsl xmlns="https://rslstandard.org/rsl">',
    '  <content url="/">',
    '    <!-- AI training and AI-input prohibited; web search and human use permitted -->',
    '    <license>',
    '      <prohibits type="usage">ai-train ai-input</prohibits>',
    '    </license>',
    '  </content>',
    '</rsl>',
  ].join("\n");
}

export function generateAllArtifacts(scan: ScanResult): GeneratedArtifacts {
  // Block everything still open; keep already-blocked ones too so the
  // snippet is a complete drop-in replacement.
  const toBlock = scan.openCrawlers.length ? scan.openCrawlers : AI_CRAWLERS.map((c) => c.userAgent);
  const robots = generateRobotsSnippet(toBlock);
  return {
    robotsSnippet: robots,
    fullRobotsTxt:
      (scan.robotsFound ? "# Append the section below to your existing robots.txt\n\n" : "") +
      robots +
      `\n# RSL 1.0 machine-readable license (Really Simple Licensing)\nLicense: ${scan.url}/license.xml`,
    aiTxt: generateAiTxt(scan.url),
    metaTags: generateMetaTags(),
    legalNotice: generateLegalNotice(scan.url),
    rslXml: generateRsl(),
  };
}

/**
 * Protection score — a sum over the multi-layer audit (src/lib/layers.ts).
 * Weights: robots.txt 40, X-Robots-Tag 15, meta noai 15, TDMRep 10,
 * ai.txt 10, aipref 5, reachable 5 (llms.txt is informational, 0).
 * The Cloudflare infrastructure check is informational only — a site's
 * "Block AI bots" dashboard setting is not observable from outside — with
 * one scored exception: robots.txt blocking Googlebot itself deducts 15,
 * shown as an explicit adjustment line so the layer weights stay intact.
 * Decoupled from ScanResult so /api/verify can score user-pasted
 * artifacts with the exact same layer builders.
 */
export function scoreFromScan(scan: ScanResult) {
  const base = scoreFromLayers(scan.layers);
  const cfDelta = scan.cloudflare?.scoreDelta ?? 0;
  const score = Math.max(0, Math.min(100, base.score + cfDelta));
  return {
    score,
    breakdown: [
      ...base.breakdown,
      ...(cfDelta !== 0
        ? [{ label: "Adjustment: Googlebot blocked (Cloudflare check)", got: cfDelta, max: 0 }]
        : []),
    ],
  };
}

